# -*- coding: utf-8 -*-
"""Task_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vYhLl4kFOFtUTxh4mZQTP3ugKEYhLi0
"""

!pip install diffusers transformers accelerate safetensors torch pillow

import torch
from diffusers import StableDiffusionImg2ImgPipeline
from PIL import Image
import matplotlib.pyplot as plt
from google.colab import files

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

prompt = input("Enter a prompt to create your image: ")

print("Upload a reference image (person / face):")
uploaded = files.upload()

image_path = next(iter(uploaded))
init_image = Image.open(image_path).convert("RGB")
init_image = init_image.resize((512, 512))

result = pipe(
    prompt=prompt,
    image=init_image,
    strength=0.65,        # lower = more like original image
    guidance_scale=7.5    # higher = more creative
).images[0]

plt.figure(figsize=(6,6))
plt.imshow(result)
plt.axis("off")